// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"time"
)

type Plugin struct {
	ID        int64
	Name      string
	Path      string
	Hash      string
	Version   string
	CreatedAt time.Time
	UpdatedAt time.Time
}
