// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package queries

import (
	"context"
	"time"
)

const createPlugin = `-- name: CreatePlugin :one
INSERT INTO plugins (
    name, path
) VALUES ( ?,? )
RETURNING id, name, path, created_at, updated_at
`

type CreatePluginParams struct {
	Name string
	Path string
}

func (q *Queries) CreatePlugin(ctx context.Context, arg CreatePluginParams) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, createPlugin, arg.Name, arg.Path)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlugin = `-- name: DeletePlugin :exec
DELETE FROM plugins
WHERE id = ?
`

func (q *Queries) DeletePlugin(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlugin, id)
	return err
}

const getPlugin = `-- name: GetPlugin :one
SELECT id, name, path, created_at, updated_at FROM plugins
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPlugin(ctx context.Context, id int64) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, getPlugin, id)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT version FROM schema_version ORDER BY version DESC LIMIT 1
`

func (q *Queries) GetSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const listPlugins = `-- name: ListPlugins :many
SELECT id, name, path, created_at, updated_at FROM plugins
ORDER BY name
`

func (q *Queries) ListPlugins(ctx context.Context) ([]Plugin, error) {
	rows, err := q.db.QueryContext(ctx, listPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plugin
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSchemaVersion = `-- name: SetSchemaVersion :exec
INSERT OR REPLACE INTO schema_version (version) VALUES (?)
`

func (q *Queries) SetSchemaVersion(ctx context.Context, version int64) error {
	_, err := q.db.ExecContext(ctx, setSchemaVersion, version)
	return err
}

const updatePlugin = `-- name: UpdatePlugin :one
UPDATE plugins
set name = ?, path = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, path, created_at, updated_at
`

type UpdatePluginParams struct {
	Name      string
	Path      string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) UpdatePlugin(ctx context.Context, arg UpdatePluginParams) (Plugin, error) {
	row := q.db.QueryRowContext(ctx, updatePlugin,
		arg.Name,
		arg.Path,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
