// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"time"
)

type PluginExample struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
