// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package queries

import (
	"context"
)

const createPluginExampleData = `-- name: CreatePluginExampleData :one
INSERT INTO plugin_example_data (
    name
) VALUES (?)
RETURNING id, name
`

func (q *Queries) CreatePluginExampleData(ctx context.Context, name string) (PluginExampleDatum, error) {
	row := q.db.QueryRowContext(ctx, createPluginExampleData, name)
	var i PluginExampleDatum
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPluginExampleData = `-- name: GetPluginExampleData :one
SELECT id, name FROM plugin_example_data
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPluginExampleData(ctx context.Context, id int64) (PluginExampleDatum, error) {
	row := q.db.QueryRowContext(ctx, getPluginExampleData, id)
	var i PluginExampleDatum
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
