// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package queries

import (
	"context"
)

const createExample = `-- name: CreateExample :one
INSERT INTO plugin_example (
    name
) VALUES ( ? )
    RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateExample(ctx context.Context, name string) (PluginExample, error) {
	row := q.db.QueryRowContext(ctx, createExample, name)
	var i PluginExample
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
